networks:
  sso_network:
    driver: bridge

services:
  # Le Reverse Proxy (Nginx Proxy Manager)
  # C'est lui qui gère le HTTPS et redirige vers les bons services
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'   # Interface de gestion (Admin)
      - '443:443'
    volumes:
      - ./infrastructure/nginx/data:/data
      - ./infrastructure/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - sso_network

  # Authelia (Le serveur d'authentification)
  authelia:
    image: 'authelia/authelia:latest'
    container_name: authelia
    restart: always
    volumes:
      - ./infrastructure/authelia:/config
    networks:
      - sso_network
    environment:
      - TZ=America/Montreal
    
    # LLDAP (Le serveur d'annuaire pour le bonus)
  lldap:
    image: 'lldap/lldap:latest'
    container_name: lldap
    restart: always
    environment:
      - TZ=America/Montreal
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_ADMIN_PASSWORD}
      - LLDAP_LDAP_BASE_DN=dc=techsolutions,dc=com
    volumes:
      - ./infrastructure/lldap:/data
    ports:
      - "17170:17170" 
      - "3890:3890"
    networks:
      - sso_network

  #Gitlab
  gitlab :
    image : 'gitlab/gitlab-ce:latest'
    container_name : gitlab
    restart : always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.mondomaine.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['omniauth_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports :
      - "2222:22"
    volumes :
      - ./infrastructure/Gitlab/config:/etc/gitlab
      - ./infrastructure/Gitlab/logs:/var/log/gitlab
      - ./infrastructure/Gitlab/data:/var/opt/gitlab
    networks :
      - sso_network

  #Jenkins
  jenkins:
    image : 'jenkins/jenkins:lts'
    container_name: jenkins
    restart : always
    user : root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./infrastructure/Jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks :
      - sso_network

  # Nextcloud (Le service de stockage de fichiers)
  nextcloud:
    image: 'nextcloud:latest'
    container_name: nextcloud
    restart: always
    ports:
      - '8081:80'  # Port HTTP pour Nextcloud (redirigé par Nginx Proxy Manager)
    volumes:
      - ./infrastructure/nextcloud/data:/var/www/html # Fichiers de configuration et utilisateurs
    environment:
      - MYSQL_DATABASE=nextcloud  # Nom de la base de données
      - MYSQL_USER=nextcloud_user      # Nom d'utilisateur de la base de données
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_USER_PASSWORD}   # Mot de passe de l'utilisateur
      - MYSQL_HOST=nextcloud_db   # Nom du service de la base de données dans Docker Compose
      - PHP_UPLOAD_LIMIT=10G      # limitations ressources pour Nextcloud
      - PHP_MEMORY_LIMIT=512M
    networks:
      - sso_network
    depends_on:
      - nextcloud_db
      - nginx-proxy

  nextcloud_db:
    image: 'mariadb:latest'
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD} # Mot de passe du root
      - MYSQL_DATABASE=nextcloud  # Nom de la base de données
      - MYSQL_USER=nextcloud_user      # Nom d'utilisateur de la base de données
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_USER_PASSWORD}   # Mot de passe de l'utilisateur
    volumes:
      - ./infrastructure/nextcloud/db:/var/lib/mysql  # Données persistantes de la base de données
    networks:
      - sso_network

  # Rocket.Chat (Le service de messagerie instantanée)
  rocketchat:
    image: 'rocketchat/rocket.chat:latest'
    container_name: rocketchat
    restart: always
    ports:
      - '3000:3000' # Port HTTP pour Rocket.Chat
    environment:
      - MONGO_URL=mongodb://rocketchat_db:27017/rocketchat  # URL de connexion à la base de données
      - ROOT_URL=http://localhost:3000             # URL de base pour Rocket.Chat, utilisée pour les liens et redirections
      - PORT=3000
    volumes:
      - ./infrastructure/rocketchat/uploads:/app/uploads    # Données persistantes pour les fichiers téléchargés dans Rocket.Chat
    networks:
      - sso_network
    depends_on:
      - rocketchat_db
      - nginx-proxy

  rocketchat_db:
    image: 'mongo:latest'
    container_name: rocketchat_db
    restart: always
    volumes:
      - ./infrastructure/rocketchat/db:/data/db # Données persistantes de la base de données
    networks:
      - sso_network

  # Jira Software (Le service de gestion de projet et de suivi des tâches)
  jira:
    image: 'atlassian/jira-software:latest'
    container_name: jira
    restart: always
    ports:
      - '8082:8080'
    volumes:
      - ./infrastructure/jira/data:/var/atlassian/application-data/jira # Données de configuration et projets de Jira
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://jira_db:5432/jira  # URL de connexion à la base de données PostgreSQL pour Jira
      - ATL_JDBC_USER=jira                                # Nom d'utilisateur de la base de données pour Jira
      - ATL_JDBC_PASSWORD=${JIRA_POSTGRES_PASSWORD}                # Mot de passe de la base de données pour Jira
    networks:
      - sso_network
    depends_on:
      - jira_db
      - nginx-proxy

  jira_db:
    image: 'postgres:latest'
    container_name: jira_db
    restart: always
    environment:
      - POSTGRES_DB=jira                    # Nom de la base de données pour Jira
      - POSTGRES_USER=jira                  # Nom d'utilisateur de la base de données pour Jira
      - POSTGRES_PASSWORD=${JIRA_POSTGRES_PASSWORD}  # Mot de passe de la base de données pour Jira
    volumes:
      - ./infrastructure/jira/db:/var/lib/postgresql # Données persistantes de la base de données
    networks:
      - sso_network

  # Confluence (Le service de documentation et de collaboration d'équipe)
  confluence:
    image: 'atlassian/confluence-server:latest'
    container_name: confluence
    restart: always
    ports:
      - '8083:8090'
    volumes:
      - ./infrastructure/confluence/data:/var/atlassian/application-data/confluence # Données de configuration et espaces de Confluence
    environment:
      - ATL_DB_TYPE=postgresql  # Type de base de données utilisée par Confluence
      - ATL_JDBC_URL=jdbc:postgresql://confluence_db:5432/confluence  # URL de connexion à la base de données
      - ATL_JDBC_USER=confluence # Nom d'utilisateur de la base de données pour Confluence 
      - ATL_JDBC_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}  # Mot de passe de la base de données pour Confluence
    networks:
      - sso_network
    depends_on:
      - confluence_db
      - nginx-proxy

  confluence_db:
    image: 'postgres:latest'
    container_name: confluence_db
    restart: always
    environment:
      - POSTGRES_DB=confluence                    # Nom de la base de données pour Confluence
      - POSTGRES_USER=confluence                  # Nom d'utilisateur de la base de données pour Confluence
      - POSTGRES_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}  # Mot de passe de la base de données pour Confluence
    volumes:
      - ./infrastructure/confluence/db:/var/lib/postgresql # Données persistantes de la base de données
    networks:
      - sso_network
