services:
  # Nginx Proxy Manager
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./infrastructure/nginx/data:/data
      - ./infrastructure/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - sso_network

  # Authelia
  authelia:
    image: 'authelia/authelia:latest'
    container_name: authelia
    restart: always
    ports:
      - "9091:9091" 
    volumes:
      - ./infrastructure/authelia:/config
    networks:
      - sso_network
    environment:
      - TZ=America/Montreal
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_KEY}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - LDAP_PASSWORD=${LLDAP_ADMIN_PASSWORD}
    depends_on:
      - lldap

  # LLDAP
  lldap:
    image: 'lldap/lldap:latest'
    container_name: lldap
    restart: always
    environment:
      - TZ=America/Montreal
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_ADMIN_PASSWORD}
      - LLDAP_LDAP_BASE_DN=dc=techsolutions,dc=com
    volumes:
      - ./infrastructure/lldap:/data
    ports:
      - "17170:17170" 
      - "3890:3890" 
    networks:
      - sso_network

  #Gitlab
  gitlab :
    image : 'gitlab/gitlab-ce:latest'
    container_name : gitlab
    restart : always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.mondomaine.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['omniauth_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports :
      - "2222:22"
    volumes :
      - ./infrastructure/Gitlab/config:/etc/gitlab
      - ./infrastructure/Gitlab/logs:/var/log/gitlab
      - ./infrastructure/Gitlab/data:/var/opt/gitlab
    networks :
      - sso_network

  #Jenkins
  jenkins:
    image : 'jenkins/jenkins:lts'
    container_name: jenkins
    restart : always
    user : root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins-data : ./infrastructure/Jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks :
      - sso_network

networks:
  sso_network:
    driver: bridge
